blank_issues_enabled: false
contact_links:
  - name: General discussion
    url: https://github.com/Kidflash1233
    about: Use profile/repo discussions or issue tracker for project-specific questions.
